

module eth_frame_packetizer #(
    parameter WIDTH               = 16'd800,
    parameter HEIGHT              = 16'd480,
    parameter PAYLOAD_BYTES       = 16'd1024,
    parameter HEADER_BYTES        = 16'd32,
    parameter SEND_FRAME_INTERVAL = 16'd30
)(
    input             rst_n,

    input             cam_pclk,
    input             img_vsync,      // one-clock frame-start pulse
    input             img_valid,
    input      [15:0] img_data,
    input      [2:0]  mode,
    input             transfer_flag,

    input             eth_tx_clk,
    input             udp_tx_req,
    input             udp_tx_done,
    output reg        udp_tx_start_en,
    output reg [31:0] udp_tx_data,
    output reg [15:0] udp_tx_byte_num
);

    localparam [31:0] IMAGE_BYTES        = WIDTH * HEIGHT * 32'd2;
    localparam [31:0] IMAGE_WORDS        = IMAGE_BYTES / 32'd4;
    localparam [15:0] PACKET_TOTAL       = (IMAGE_BYTES + PAYLOAD_BYTES - 1) / PAYLOAD_BYTES;
    localparam [8:0]  HEADER_WORDS       = HEADER_BYTES / 4;
    localparam [8:0]  PAYLOAD_WORDS_FULL = (PAYLOAD_BYTES + 3) / 4;

    // -------------------------------------------------------------------------
    // transfer flag CDC
    // -------------------------------------------------------------------------
    reg transfer_flag_cam_d0;
    reg transfer_flag_cam_d1;
    reg transfer_flag_eth_d0;
    reg transfer_flag_eth_d1;

    always @(posedge cam_pclk or negedge rst_n) begin
        if(!rst_n) begin
            transfer_flag_cam_d0 <= 1'b0;
            transfer_flag_cam_d1 <= 1'b0;
        end else begin
            transfer_flag_cam_d0 <= transfer_flag;
            transfer_flag_cam_d1 <= transfer_flag_cam_d0;
        end
    end

    always @(posedge eth_tx_clk or negedge rst_n) begin
        if(!rst_n) begin
            transfer_flag_eth_d0 <= 1'b0;
            transfer_flag_eth_d1 <= 1'b0;
        end else begin
            transfer_flag_eth_d0 <= transfer_flag;
            transfer_flag_eth_d1 <= transfer_flag_eth_d0;
        end
    end

    wire transfer_flag_cam = transfer_flag_cam_d1;
    wire transfer_flag_eth = transfer_flag_eth_d1;

    // -------------------------------------------------------------------------
    // frame-start pulse synchronization inside cam_pclk domain
    // img_vsync is already generated by lcd_driver at first active output pixel.
    // Use rising edge to make the packetizer tolerant to wider pulses.
    // -------------------------------------------------------------------------
    reg img_vsync_d0;
    reg img_vsync_d1;

    always @(posedge cam_pclk or negedge rst_n) begin
        if(!rst_n) begin
            img_vsync_d0 <= 1'b0;
            img_vsync_d1 <= 1'b0;
        end else begin
            img_vsync_d0 <= img_vsync;
            img_vsync_d1 <= img_vsync_d0;
        end
    end

    wire frame_start_cam = img_vsync_d0 & (~img_vsync_d1);

    // -------------------------------------------------------------------------
    // eth busy synchronizer back to cam_pclk domain.
    // It prevents selecting a new source frame before the previous UDP frame ends.
    // -------------------------------------------------------------------------
    reg eth_frame_busy;
    reg eth_busy_cam_d0;
    reg eth_busy_cam_d1;

    always @(posedge cam_pclk or negedge rst_n) begin
        if(!rst_n) begin
            eth_busy_cam_d0 <= 1'b0;
            eth_busy_cam_d1 <= 1'b0;
        end else begin
            eth_busy_cam_d0 <= eth_frame_busy;
            eth_busy_cam_d1 <= eth_busy_cam_d0;
        end
    end

    wire eth_busy_cam = eth_busy_cam_d1;

    // -------------------------------------------------------------------------
    // cam_pclk domain: select a real LCD frame and write payload into FIFO.
    // -------------------------------------------------------------------------
    reg [15:0] frame_skip_cnt;
    reg        frame_capture;
    reg        wr_half;
    reg [15:0] pix_d;
    reg        wr_fifo_en;
    reg [31:0] wr_fifo_data;
    reg [31:0] wr_word_cnt;
    reg [2:0]  mode_cam_latched;
    reg        frame_start_toggle_cam;

    wire fifo_wr_full;

    always @(posedge cam_pclk or negedge rst_n) begin
        if(!rst_n) begin
            frame_skip_cnt         <= 16'd0;
            frame_capture          <= 1'b0;
            wr_half                <= 1'b0;
            pix_d                  <= 16'd0;
            wr_fifo_en             <= 1'b0;
            wr_fifo_data           <= 32'd0;
            wr_word_cnt            <= 32'd0;
            mode_cam_latched       <= 3'd3;
            frame_start_toggle_cam <= 1'b0;
        end else begin
            wr_fifo_en <= 1'b0;

            if(!transfer_flag_cam) begin
                frame_skip_cnt         <= 16'd0;
                frame_capture          <= 1'b0;
                wr_half                <= 1'b0;
                pix_d                  <= 16'd0;
                wr_word_cnt            <= 32'd0;
                mode_cam_latched       <= mode;
                frame_start_toggle_cam <= 1'b0;
            end else begin
                if(frame_start_cam) begin
                    if(SEND_FRAME_INTERVAL <= 16'd1) begin
                        frame_skip_cnt <= 16'd0;
                    end else if(frame_skip_cnt >= (SEND_FRAME_INTERVAL - 16'd1)) begin
                        frame_skip_cnt <= 16'd0;
                    end else begin
                        frame_skip_cnt <= frame_skip_cnt + 16'd1;
                    end

                    if((!frame_capture) && (!eth_busy_cam) &&
                       ((SEND_FRAME_INTERVAL <= 16'd1) ||
                        (frame_skip_cnt >= (SEND_FRAME_INTERVAL - 16'd1)))) begin
                        frame_capture          <= 1'b1;
                        wr_half                <= 1'b0;
                        wr_word_cnt            <= 32'd0;
                        mode_cam_latched       <= mode;
                        frame_start_toggle_cam <= ~frame_start_toggle_cam;
                    end
                end

                if(frame_capture && img_valid) begin
                    wr_half <= ~wr_half;
                    pix_d   <= img_data;

                    if(wr_half) begin
                        if(!fifo_wr_full) begin
                            wr_fifo_en   <= 1'b1;
                            wr_fifo_data <= {pix_d, img_data};

                            if(wr_word_cnt >= (IMAGE_WORDS - 32'd1)) begin
                                frame_capture <= 1'b0;
                                wr_word_cnt   <= 32'd0;
                                wr_half       <= 1'b0;
                            end else begin
                                wr_word_cnt <= wr_word_cnt + 32'd1;
                            end
                        end
                    end
                end
            end
        end
    end

    // -------------------------------------------------------------------------
    // frame-start toggle and mode CDC into eth_tx_clk domain
    // -------------------------------------------------------------------------
    reg frame_toggle_eth_d0;
    reg frame_toggle_eth_d1;
    reg frame_toggle_eth_d2;

    always @(posedge eth_tx_clk or negedge rst_n) begin
        if(!rst_n) begin
            frame_toggle_eth_d0 <= 1'b0;
            frame_toggle_eth_d1 <= 1'b0;
            frame_toggle_eth_d2 <= 1'b0;
        end else begin
            frame_toggle_eth_d0 <= frame_start_toggle_cam;
            frame_toggle_eth_d1 <= frame_toggle_eth_d0;
            frame_toggle_eth_d2 <= frame_toggle_eth_d1;
        end
    end

    wire new_frame_eth = frame_toggle_eth_d1 ^ frame_toggle_eth_d2;

    reg [2:0] mode_eth_d0;
    reg [2:0] mode_eth_d1;

    always @(posedge eth_tx_clk or negedge rst_n) begin
        if(!rst_n) begin
            mode_eth_d0 <= 3'd3;
            mode_eth_d1 <= 3'd3;
        end else begin
            mode_eth_d0 <= mode_cam_latched;
            mode_eth_d1 <= mode_eth_d0;
        end
    end

    wire [2:0] mode_eth = mode_eth_d1;

    // -------------------------------------------------------------------------
    // async FIFO, payload only
    // -------------------------------------------------------------------------
    wire [10:0] fifo_rdusedw;
    wire [31:0] fifo_rd_data;
    wire        fifo_rd_en;
    wire        fifo_rd_empty;

    async_fifo_1024x32b u_async_fifo (
        .wr_clk        (cam_pclk),
        .wr_rst        (~transfer_flag_cam),
        .wr_en         (wr_fifo_en),
        .wr_data       (wr_fifo_data),
        .wr_full       (fifo_wr_full),
        .almost_full   (),
        .rd_clk        (eth_tx_clk),
        .rd_rst        (~transfer_flag_eth),
        .rd_en         (fifo_rd_en),
        .rd_data       (fifo_rd_data),
        .rd_empty      (fifo_rd_empty),
        .rd_water_level(fifo_rdusedw),
        .almost_empty  ()
    );

    // -------------------------------------------------------------------------
    // eth_tx_clk domain: UDP packet scheduler
    // -------------------------------------------------------------------------
    reg        tx_busy;
    reg        sending;
    reg        first_req_seen;
    reg [8:0]  tx_word_cnt;

    reg [31:0] frame_id_eth;
    reg [15:0] packet_id_eth;
    reg [31:0] byte_offset_eth;

    reg [15:0] payload_len_eth;
    reg [8:0]  payload_words_eth;
    reg [8:0]  total_words_eth;

    wire [31:0] remain_bytes_eth;
    wire [15:0] next_payload_len_eth;
    wire [8:0]  next_payload_words_eth;
    wire [10:0] next_payload_words_eth_ext;
    wire [15:0] checksum16_eth;

    assign remain_bytes_eth = IMAGE_BYTES - byte_offset_eth;

    assign next_payload_len_eth =
        (remain_bytes_eth >= PAYLOAD_BYTES) ? PAYLOAD_BYTES[15:0] : remain_bytes_eth[15:0];

    assign next_payload_words_eth = (next_payload_len_eth + 16'd3) >> 2;
    assign next_payload_words_eth_ext = {2'b00, next_payload_words_eth};

    assign checksum16_eth =
        frame_id_eth[15:0] ^
        {13'd0, mode_eth} ^
        WIDTH ^
        HEIGHT ^
        packet_id_eth ^
        PACKET_TOTAL ^
        payload_len_eth ^
        byte_offset_eth[15:0] ^
        byte_offset_eth[31:16];

    // Prefetch one payload word from synchronous FIFO when header word7 is requested.
    assign fifo_rd_en =
        sending &&
        first_req_seen &&
        udp_tx_req &&
        transfer_flag_eth &&
        (tx_word_cnt >= (HEADER_WORDS - 9'd1)) &&
        (tx_word_cnt <  (total_words_eth - 9'd1));

    always @(posedge eth_tx_clk or negedge rst_n) begin
        if(!rst_n) begin
            udp_tx_start_en   <= 1'b0;
            udp_tx_byte_num   <= HEADER_BYTES + PAYLOAD_BYTES;
            tx_busy           <= 1'b0;
            sending           <= 1'b0;
            first_req_seen    <= 1'b0;
            tx_word_cnt       <= 9'd0;
            eth_frame_busy    <= 1'b0;
            frame_id_eth      <= 32'd0;
            packet_id_eth     <= 16'd0;
            byte_offset_eth   <= 32'd0;
            payload_len_eth   <= PAYLOAD_BYTES;
            payload_words_eth <= PAYLOAD_WORDS_FULL;
            total_words_eth   <= HEADER_WORDS + PAYLOAD_WORDS_FULL;
        end else begin
            udp_tx_start_en <= 1'b0;

            if(!transfer_flag_eth) begin
                tx_busy           <= 1'b0;
                sending           <= 1'b0;
                first_req_seen    <= 1'b0;
                tx_word_cnt       <= 9'd0;
                eth_frame_busy    <= 1'b0;
                frame_id_eth      <= 32'd0;
                packet_id_eth     <= 16'd0;
                byte_offset_eth   <= 32'd0;
                payload_len_eth   <= PAYLOAD_BYTES;
                payload_words_eth <= PAYLOAD_WORDS_FULL;
                total_words_eth   <= HEADER_WORDS + PAYLOAD_WORDS_FULL;
                udp_tx_byte_num   <= HEADER_BYTES + PAYLOAD_BYTES;
            end else begin
                if(new_frame_eth && !eth_frame_busy && !tx_busy && !sending) begin
                    eth_frame_busy  <= 1'b1;
                    frame_id_eth    <= frame_id_eth + 32'd1;
                    packet_id_eth   <= 16'd0;
                    byte_offset_eth <= 32'd0;
                end

                if(eth_frame_busy && !tx_busy && !sending &&
                   (remain_bytes_eth != 32'd0) &&
                   (fifo_rdusedw >= next_payload_words_eth_ext)) begin
                    payload_len_eth   <= next_payload_len_eth;
                    payload_words_eth <= next_payload_words_eth;
                    total_words_eth   <= HEADER_WORDS + next_payload_words_eth;
                    udp_tx_byte_num   <= HEADER_BYTES + next_payload_len_eth;
                    udp_tx_start_en   <= 1'b1;
                    tx_busy           <= 1'b1;
                    sending           <= 1'b1;
                    first_req_seen    <= 1'b0;
                    tx_word_cnt       <= 9'd0;
                end

                if(sending && udp_tx_req) begin
                    if(!first_req_seen) begin
                        first_req_seen <= 1'b1;
                        tx_word_cnt    <= 9'd0;
                    end else begin
                        if(tx_word_cnt >= (total_words_eth - 9'd1)) begin
                            tx_word_cnt    <= 9'd0;
                            sending        <= 1'b0;
                            first_req_seen <= 1'b0;
                        end else begin
                            tx_word_cnt <= tx_word_cnt + 9'd1;
                        end
                    end
                end

                if(udp_tx_done) begin
                    tx_busy        <= 1'b0;
                    sending        <= 1'b0;
                    first_req_seen <= 1'b0;
                    tx_word_cnt    <= 9'd0;

                    if(packet_id_eth + 16'd1 >= PACKET_TOTAL) begin
                        packet_id_eth   <= 16'd0;
                        byte_offset_eth <= 32'd0;
                        eth_frame_busy  <= 1'b0;
                    end else begin
                        packet_id_eth   <= packet_id_eth + 16'd1;
                        byte_offset_eth <= byte_offset_eth + payload_len_eth;
                    end
                end
            end
        end
    end

    // -------------------------------------------------------------------------
    // UDP payload data mux: 32-byte FPGV header + RGB565 payload
    // -------------------------------------------------------------------------
    always @(*) begin
        if(!transfer_flag_eth) begin
            udp_tx_data = 32'd0;
        end else begin
            case(tx_word_cnt)
                9'd0:    udp_tx_data = 32'h46504756;                    // FPGV
                9'd1:    udp_tx_data = {8'h01, {5'd0, mode_eth}, 8'd0, 8'd0};
                9'd2:    udp_tx_data = frame_id_eth;
                9'd3:    udp_tx_data = {WIDTH, HEIGHT};
                9'd4:    udp_tx_data = {packet_id_eth, PACKET_TOTAL};
                9'd5:    udp_tx_data = {payload_len_eth, 16'd0};
                9'd6:    udp_tx_data = byte_offset_eth;
                9'd7:    udp_tx_data = {checksum16_eth, 16'd0};
                default: udp_tx_data = fifo_rd_data;
            endcase
        end
    end

endmodule
