`default_nettype wire
`timescale 1ns / 1ps

module Main_Flow(
    input           free_clk,
    input           rstn,
    output          u10_rstn_out,
    output          u10_mdc_o,
    output          u10_mdio,
    output          u2_rstn_out,
    output          u2_mdc_o,
    output          u2_mdio,
    output [7:0]    led,
    input           i_p_refckn_0,
    input           i_p_refckp_0,
    input           i_p_l0rxn,
    input           i_p_l0rxp,
    input           i_p_l1rxn,
    input           i_p_l1rxp,
    input           i_p_l2rxn,
    input           i_p_l2rxp,
    input           i_p_l3rxn,
    input           i_p_l3rxp,
    output          o_p_l0txn,
    output          o_p_l0txp,
    output          o_p_l1txn,
    output          o_p_l1txp,
    output          o_p_l2txn,
    output          o_p_l2txp,
    output          o_p_l3txn,
    output          o_p_l3txp,
    output [2:0]    u2_ch0_led,
    output [2:0]    u2_ch1_led,
    output [2:0]    u2_ch2_led,
    output [2:0]    u2_ch3_led,
    output [2:0]    u10_ch0_led,
    output [2:0]    u10_ch1_led,
    output [2:0]    u10_ch2_led,
    output [2:0]    u10_ch3_led,
    output [1:0]    tx_disable
);

    mesethernet_test u_mesethernet_test (
        .free_clk(free_clk),
        .rstn(rstn),
        .u10_rstn_out(u10_rstn_out),
        .u10_mdc_o(u10_mdc_o),
        .u10_mdio(u10_mdio),
        .u2_rstn_out(u2_rstn_out),
        .u2_mdc_o(u2_mdc_o),
        .u2_mdio(u2_mdio),
        .led(led),
        .i_p_refckn_0(i_p_refckn_0),
        .i_p_refckp_0(i_p_refckp_0),
        .i_p_l0rxn(i_p_l0rxn),
        .i_p_l0rxp(i_p_l0rxp),
        .i_p_l1rxn(i_p_l1rxn),
        .i_p_l1rxp(i_p_l1rxp),
        .i_p_l2rxn(i_p_l2rxn),
        .i_p_l2rxp(i_p_l2rxp),
        .i_p_l3rxn(i_p_l3rxn),
        .i_p_l3rxp(i_p_l3rxp),
        .o_p_l0txn(o_p_l0txn),
        .o_p_l0txp(o_p_l0txp),
        .o_p_l1txn(o_p_l1txn),
        .o_p_l1txp(o_p_l1txp),
        .o_p_l2txn(o_p_l2txn),
        .o_p_l2txp(o_p_l2txp),
        .o_p_l3txn(o_p_l3txn),
        .o_p_l3txp(o_p_l3txp),
        .u2_ch0_led(u2_ch0_led),
        .u2_ch1_led(u2_ch1_led),
        .u2_ch2_led(u2_ch2_led),
        .u2_ch3_led(u2_ch3_led),
        .u10_ch0_led(u10_ch0_led),
        .u10_ch1_led(u10_ch1_led),
        .u10_ch2_led(u10_ch2_led),
        .u10_ch3_led(u10_ch3_led),
        .tx_disable(tx_disable)
    );

endmodule
